// eslint-disable-next-line @typescript-eslint/no-require-imports
import tinycolor = require('tinycolor2');

export default {
  primaryColor: tinycolor('#07C160').toHexString(),
  adGreen: tinycolor('#07C160').toHexString(),
  adOrange: tinycolor('#EDA20C').toHexString(),
  adBlue: tinycolor('#2B7BD6').toHexString(),
  adRed: tinycolor('#D9514C').toHexString(),
  transparentGray50: tinycolor('rgba(0,0,0,0.02)').toRgbString(),
  transparentGray100: tinycolor('rgba(0,0,0,0.06)').toRgbString(),
  transparentGray200: tinycolor('rgba(0,0,0,0.08)').toRgbString(),
  transparentGray300: tinycolor('rgba(0,0,0,0.1)').toRgbString(),
  transparentGray400: tinycolor('rgba(0,0,0,0.12)').toRgbString(),
  transparentGray500: tinycolor('rgba(0,0,0,0.16)').toRgbString(),
  transparentGray600: tinycolor('rgba(0,0,0,0.22)').toRgbString(),
  transparentGray700: tinycolor('rgba(0,0,0,0.36)').toRgbString(),
  transparentGray800: tinycolor('rgba(0,0,0,0.58)').toRgbString(),
  transparentGray900: tinycolor('rgba(0,0,0,0.88)').toRgbString(),
  gray50: tinycolor('#FAFAFA').toHexString(),
  gray100: tinycolor('#F2F2F2').toHexString(),
  gray200: tinycolor('#EBEBEB').toHexString(),
  gray300: tinycolor('#E6E6E6').toHexString(),
  gray400: tinycolor('#E0E0E0').toHexString(),
  gray500: tinycolor('#D6D6D6').toHexString(),
  gray600: tinycolor('#C7C7C7').toHexString(),
  gray700: tinycolor('#A3A3A3').toHexString(),
  gray800: tinycolor('#6B6B6B').toHexString(),
  gray900: tinycolor('#1F1F1F').toHexString(),

  chartBlue: tinycolor('#3E79F0').toHexString(),
  chartBlue2: tinycolor('#5E94FF').toHexString(),
  chartLightBlue: tinycolor('#9AD6FF').toHexString(),
  chartLightBlue2: tinycolor('#BBE4FF').toHexString(),
  chartOrange: tinycolor('#FFAE19').toHexString(),
  chartOrange2: tinycolor('#FFCC41').toHexString(),
  chartGreen: tinycolor('#76C84D').toHexString(),
  chartGreen2: tinycolor('#96D960').toHexString(),
  chartPurple: tinycolor('#8E84FD').toHexString(),
  chartPurple2: tinycolor('#BCA1FF').toHexString(),
  chartRed: tinycolor('#FF6D5E').toHexString(),
  chartRed2: tinycolor('#FF9C92').toHexString(),
};
